version: '3'
services:
  servidorweb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    container_name: servidorWeb1
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=pebank
      - MYSQL_USER=peter
      - MYSQL_PASSWORD=peter01
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    container_name: db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data:
    driver: local